'use strict';
(()=>{
const $=id=>document.getElementById(id);
const state={month:null,programs:[],runs:[],items:[],selected:null};
const requestId=()=>crypto.randomUUID();
const text=(id,v)=>{if($(id))$(id).textContent=String(v??'');};
const el=(tag,value,cls)=>{const x=document.createElement(tag);if(value!==undefined)x.textContent=String(value);if(cls)x.className=cls;return x;};
async function api(path,options={}){const r=await fetch(path,{credentials:'same-origin',cache:'no-store',redirect:'error',...options});if(!r.ok){const e=new Error('request_failed');e.status=r.status;try{e.detail=(await r.json()).detail}catch{}throw e;}return r.status===204?null:r.json();}
async function csrf(){return (await api('/auth/csrf')).csrf_token;}
async function post(path,body){const token=await csrf();return api(path,{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':token},body:JSON.stringify(body)});}
function kstMonth(){const p=new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit'}).formatToParts(new Date());const o=Object.fromEntries(p.map(x=>[x.type,x.value]));return o.year+'-'+o.month;}
function shiftMonth(value,delta){const [y,m]=value.split('-').map(Number);const d=new Date(Date.UTC(y,m-1+delta,1));return d.getUTCFullYear()+'-'+String(d.getUTCMonth()+1).padStart(2,'0');}
function shiftDate(value,days){const [y,m,d]=value.split('-').map(Number);const x=new Date(Date.UTC(y,m-1,d+days));return x.toISOString().slice(0,10);}
function localParts(value){const parts=new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(value));const o=Object.fromEntries(parts.map(x=>[x.type,x.value]));return {date:o.year+'-'+o.month+'-'+o.day,time:o.hour+':'+o.minute};}
function iso(date,time){return date+'T'+time+':00+09:00';}
function color(item){const s=(item.category_label||'')+' '+(item.program_id||'')+' '+(item.event_type||'');if(s.includes('Pre')||s.includes('프리')||s.includes('pre-richon'))return'#00b622';if(s.includes('재개발'))return'#3978f6';if(s.includes('인테리어'))return'#ff9f26';if(s.includes('무료 브리핑')||s.includes('BRIEFING'))return'#d8bd78';if(s.includes('스터디 전체')||s.includes('STUDY_ALL'))return'#c000db';if(s.includes('스터디'))return'#ff5757';if(s.includes('FIELD_TRIP')||s.includes('임장'))return'#008f83';if(s.includes('SPECIAL')||s.includes('특강'))return'#7258d8';return'#777';}
function fill(select,items,blank){select.replaceChildren();const z=el('option',blank);z.value='';select.append(z);for(const i of items){const o=el('option',i.label);o.value=i.value;select.append(o);}}
function fillRuns(programId,selected=''){const rows=state.runs.filter(x=>!x.archived&&(!programId||x.program_id===programId)).map(x=>({value:x.run_id,label:x.program_title+(x.cohort_label?' / '+x.cohort_label:'')}));fill($('run'),rows,'기수 선택');$('run').value=selected;}
function renderPrograms(){fill($('program'),state.programs.filter(x=>!x.archived).map(x=>({value:x.program_id,label:x.title})),'프로그램 선택');}
function eventButton(item){const b=el('button',undefined,'calendar-event'+(item.cancelled?' cancelled':''));b.type='button';b.style.setProperty('--event-color',color(item));const p=localParts(item.starts_at);const line=el('b');const dot=el('span',undefined,'event-dot');line.append(dot,document.createTextNode(p.time+' '+item.category_label));b.append(line,el('small',item.title));b.addEventListener('click',()=>edit(item));return b;}
function renderCalendar(){const [y,m]=state.month.split('-').map(Number);text('month-label',y+'년 '+m+'월');const first=new Date(Date.UTC(y,m-1,1)).getUTCDay();const days=new Date(Date.UTC(y,m,0)).getUTCDate();const total=Math.max(35,Math.ceil((first+days)/7)*7);const by={};for(const i of state.items){const d=localParts(i.starts_at).date;(by[d]??=[]).push(i);}const grid=$('calendar-grid');grid.replaceChildren();for(let n=0;n<total;n++){const d=n-first+1;const cell=el('div',undefined,'day-cell'+(d<1||d>days?' outside':''));if(d>=1&&d<=days){const key=state.month+'-'+String(d).padStart(2,'0');cell.append(el('div',d,'day-number'));for(const item of by[key]||[])cell.append(eventButton(item));}grid.append(cell);}const agenda=$('calendar-agenda');agenda.replaceChildren();for(const key of Object.keys(by).sort()){const box=el('section',undefined,'agenda-day');const date=new Date(key+'T00:00:00+09:00');box.append(el('h3',new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',month:'long',day:'numeric',weekday:'short'}).format(date)));for(const item of by[key])box.append(eventButton(item));agenda.append(box);}text('calendar-status',state.items.length?'':'등록된 일정이 없습니다.');}
function toggleKind(){const session=$('kind').value==='session';$('session-fields').hidden=!session;$('session-links').hidden=!session;$('event-fields').hidden=session;}
function resetEditor(){state.selected=null;$('calendar-form').reset();$('kind').value='session';$('calendar-form').elements.reason.value='캘린더 일정 등록';$('calendar-form').elements.is_public.checked=true;renderPrograms();fillRuns('');toggleKind();text('editor-title','일정 추가');$('clone-week').hidden=true;text('editor-status','');}
function edit(item){state.selected=item;const f=$('calendar-form').elements;$('kind').value=item.kind;toggleKind();const p=localParts(item.starts_at);f.date.value=p.date;f.start_time.value=p.time;f.end_time.value=item.ends_at?localParts(item.ends_at).time:'';f.title.value=item.title||'';f.presenter_name.value=item.presenter_name||'';f.cancelled.checked=!!item.cancelled;f.reason.value='캘린더 일정 수정';if(item.kind==='session'){$('program').value=item.program_id;fillRuns(item.program_id,item.run_id);f.sequence_no.value=item.sequence_no;f.video_url.value=item.video_url||'';f.material_url.value=item.material_url||'';}else{f.event_type.value=item.event_type;f.is_public.checked=!!item.is_public;}text('editor-title','일정 수정');$('clone-week').hidden=false;$('editor-title').scrollIntoView({behavior:'smooth',block:'center'});}
async function loadCatalog(){const [p,r]=await Promise.all([api('/portal/api/admin/learning/programs'),api('/portal/api/admin/learning/runs')]);state.programs=p.items;state.runs=r.items;renderPrograms();fillRuns('');}
async function loadMonth(){text('calendar-status','불러오는 중입니다.');const data=await api('/portal/api/admin/learning/calendar?'+new URLSearchParams({month:state.month}));state.items=data.items;renderCalendar();}
async function boot(){try{const me=await api('/portal/api/me');if(me.role!=='admin')throw Object.assign(new Error(),{status:403});$('gate').hidden=true;$('content').hidden=false;state.month=kstMonth();await loadCatalog();resetEditor();await loadMonth();}catch(e){text('gate-text',e.status===403?'관리자 권한이 필요합니다.':'로그인 또는 연결 상태를 확인해 주세요.');$('retry').hidden=false;}}
$('retry').addEventListener('click',boot);$('kind').addEventListener('change',toggleKind);$('program').addEventListener('change',()=>fillRuns($('program').value));$('reset-editor').addEventListener('click',resetEditor);$('today').addEventListener('click',async()=>{state.month=kstMonth();await loadMonth();});$('prev-month').addEventListener('click',async()=>{state.month=shiftMonth(state.month,-1);await loadMonth();});$('next-month').addEventListener('click',async()=>{state.month=shiftMonth(state.month,1);await loadMonth();});
$('clone-week').addEventListener('click',()=>{const f=$('calendar-form').elements;f.date.value=shiftDate(f.date.value,7);if($('kind').value==='session'&&f.sequence_no.value)f.sequence_no.value=String(Number(f.sequence_no.value)+1);f.cancelled.checked=false;f.reason.value='다음 주 일정 복제';state.selected=null;text('editor-title','복제한 새 일정');$('clone-week').hidden=true;text('editor-status','날짜를 7일 뒤로 옮겼습니다. 제목과 담당자를 확인한 뒤 저장하세요.');});
$('calendar-form').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget.elements;if(!f.date.value||!f.start_time.value){text('editor-status','날짜와 시작 시간을 입력해 주세요.');return;}const common={request_id:requestId(),reason:f.reason.value,title:f.title.value.trim(),starts_at:iso(f.date.value,f.start_time.value),ends_at:f.end_time.value?iso(f.date.value,f.end_time.value):null};let path,body;if(f.kind.value==='session'){if(!f.run_id.value||!f.sequence_no.value){text('editor-status','프로그램 / 기수 / 회차를 입력해 주세요.');return;}const session={...common,mentor_name:f.presenter_name.value.trim()||null,video_url:f.video_url.value.trim()||null,material_url:f.material_url.value.trim()||null};if(state.selected){path='/portal/api/admin/learning/sessions/update';body={...session,session_id:state.selected.session_id,version:state.selected.version,cancelled:f.cancelled.checked};}else{path='/portal/api/admin/learning/sessions';body={...session,run_id:f.run_id.value,sequence_no:Number(f.sequence_no.value)};}}else{const event={...common,presenter_name:f.presenter_name.value.trim()||null,event_type:f.event_type.value,is_public:f.is_public.checked};if(state.selected){path='/portal/api/admin/learning/calendar-events/update';body={...event,event_id:state.selected.event_id,version:state.selected.version,cancelled:f.cancelled.checked};}else{path='/portal/api/admin/learning/calendar-events';body=event;}}try{await post(path,body);state.month=f.date.value.slice(0,7);resetEditor();text('editor-status','저장했습니다.');await loadMonth();}catch(x){text('editor-status','저장하지 못했습니다: '+(x.detail||x.status||''));}});
$('logout').addEventListener('click',async()=>{try{const t=await csrf();await api('/auth/logout',{method:'POST',headers:{'X-CSRF-Token':t}});location.href='/';}catch{text('action-status','로그아웃하지 못했습니다.');}});
boot();
})();
