'use strict';
(()=>{
const $=id=>document.getElementById(id);
const state={month:null,items:[],selected:null};
const requestId=()=>crypto.randomUUID();
const text=(id,v)=>{if($(id))$(id).textContent=String(v??'');};
const el=(tag,value,cls)=>{const x=document.createElement(tag);if(value!==undefined)x.textContent=String(value);if(cls)x.className=cls;return x;};
async function api(path,options={}){const r=await fetch(path,{credentials:'same-origin',cache:'no-store',redirect:'error',...options});if(!r.ok){const e=new Error('request_failed');e.status=r.status;try{e.detail=(await r.json()).detail}catch{}throw e;}return r.status===204?null:r.json();}
async function csrf(){return (await api('/auth/csrf')).csrf_token;}
async function post(path,body){const token=await csrf();return api(path,{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':token},body:JSON.stringify(body)});}
function kstToday(){const p=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const o=Object.fromEntries(p.map(x=>[x.type,x.value]));return o.year+'-'+o.month+'-'+o.day;}
function kstMonth(){return kstToday().slice(0,7);}
function shiftMonth(value,delta){const [y,m]=value.split('-').map(Number);const d=new Date(Date.UTC(y,m-1+delta,1));return d.getUTCFullYear()+'-'+String(d.getUTCMonth()+1).padStart(2,'0');}
function formValues(){const f=$('calendar-form').elements;return {event_date:f.event_date.value,color_hex:f.color_hex.value,course_label:f.course_label.value.trim(),content_text:f.content_text.value.trim()};}
function valid(values){if(!values.event_date||!values.course_label||!values.content_text){text('editor-status','날짜 / 과정 / 내용을 입력해 주세요.');return false;}return true;}
function updateColor(){ $('color-preview').style.setProperty('--calendar-color',$('color-select').value); }
function eventButton(item){const b=el('button',undefined,'calendar-event');b.type='button';b.style.setProperty('--event-color',item.color_hex);const line=el('b');const dot=el('span',undefined,'event-dot');line.append(dot,document.createTextNode(item.course_label));b.append(line,el('small',item.content_text));b.addEventListener('click',event=>{event.stopPropagation();edit(item);});return b;}
function resetEditor(date){state.selected=null;$('calendar-form').reset();$('calendar-form').elements.event_date.value=date||kstToday();$('color-select').value='#3978F6';updateColor();text('editor-title','일정 추가');$('copy-event').hidden=true;$('delete-event').hidden=true;text('editor-status','');}
function edit(item){state.selected=item;const f=$('calendar-form').elements;f.event_date.value=item.event_date;f.color_hex.value=item.color_hex;f.course_label.value=item.course_label;f.content_text.value=item.content_text;updateColor();text('editor-title','일정 수정');$('copy-event').hidden=false;$('delete-event').hidden=false;text('editor-status','');$('editor-title').scrollIntoView({behavior:'smooth',block:'center'});}
function renderCalendar(){const [y,m]=state.month.split('-').map(Number);text('month-label',y+'년 '+m+'월');const first=new Date(Date.UTC(y,m-1,1)).getUTCDay();const days=new Date(Date.UTC(y,m,0)).getUTCDate();const total=Math.max(35,Math.ceil((first+days)/7)*7);const by={};for(const item of state.items)(by[item.event_date]??=[]).push(item);const grid=$('calendar-grid');grid.replaceChildren();for(let n=0;n<total;n++){const d=n-first+1;const cell=el('div',undefined,'day-cell'+(d<1||d>days?' outside':''));if(d>=1&&d<=days){const key=state.month+'-'+String(d).padStart(2,'0');cell.append(el('div',d,'day-number'));cell.addEventListener('click',()=>resetEditor(key));for(const item of by[key]||[])cell.append(eventButton(item));}grid.append(cell);}const agenda=$('calendar-agenda');agenda.replaceChildren();for(const key of Object.keys(by).sort()){const box=el('section',undefined,'agenda-day');const date=new Date(key+'T00:00:00+09:00');box.append(el('h3',new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',month:'long',day:'numeric',weekday:'short'}).format(date)));for(const item of by[key])box.append(eventButton(item));agenda.append(box);}text('calendar-status',state.items.length?'':'등록된 일정이 없습니다.');}
async function loadMonth(){text('calendar-status','불러오는 중입니다.');const data=await api('/portal/api/admin/learning/calendar?'+new URLSearchParams({month:state.month}));state.items=data.items;renderCalendar();}
async function selectCreated(result,date){state.month=date.slice(0,7);await loadMonth();const item=state.items.find(x=>x.event_id===result.event_id);if(item)edit(item);else resetEditor(date);}
async function boot(){try{const me=await api('/portal/api/me');if(me.role!=='admin')throw Object.assign(new Error(),{status:403});$('gate').hidden=true;$('content').hidden=false;state.month=kstMonth();resetEditor();await loadMonth();}catch(e){text('gate-text',e.status===403?'관리자 권한이 필요합니다.':'로그인 또는 연결 상태를 확인해 주세요.');$('retry').hidden=false;}}
$('retry').addEventListener('click',boot);$('reset-editor').addEventListener('click',()=>resetEditor());$('color-select').addEventListener('change',updateColor);
$('today').addEventListener('click',async()=>{state.month=kstMonth();await loadMonth();});$('prev-month').addEventListener('click',async()=>{state.month=shiftMonth(state.month,-1);await loadMonth();});$('next-month').addEventListener('click',async()=>{state.month=shiftMonth(state.month,1);await loadMonth();});
$('calendar-form').addEventListener('submit',async e=>{e.preventDefault();const values=formValues();if(!valid(values))return;const updating=!!state.selected;const path=updating?'/portal/api/admin/learning/calendar-events/update':'/portal/api/admin/learning/calendar-events';const body={request_id:requestId(),reason:updating?'캘린더 일정 수정':'캘린더 일정 등록',...values};if(updating)Object.assign(body,{event_id:state.selected.event_id,version:state.selected.version,deleted:false});try{const result=await post(path,body);text('editor-status','저장했습니다.');await selectCreated(result,values.event_date);}catch(x){text('editor-status','저장하지 못했습니다: '+(x.detail||x.status||''));}});
$('copy-event').addEventListener('click',async()=>{if(!state.selected)return;const values=formValues();if(!valid(values))return;try{const result=await post('/portal/api/admin/learning/calendar-events',{request_id:requestId(),reason:'캘린더 일정 복사',...values});text('editor-status','선택한 날짜에 복사했습니다.');await selectCreated(result,values.event_date);}catch(x){text('editor-status','복사하지 못했습니다: '+(x.detail||x.status||''));}});
$('delete-event').addEventListener('click',async()=>{if(!state.selected||!confirm('이 일정을 삭제할까요?'))return;const item=state.selected;try{await post('/portal/api/admin/learning/calendar-events/update',{request_id:requestId(),reason:'캘린더 일정 삭제',event_id:item.event_id,version:item.version,event_date:item.event_date,color_hex:item.color_hex,course_label:item.course_label,content_text:item.content_text,deleted:true});const month=item.event_date.slice(0,7);resetEditor();state.month=month;await loadMonth();text('editor-status','삭제했습니다.');}catch(x){text('editor-status','삭제하지 못했습니다: '+(x.detail||x.status||''));}});
$('logout').addEventListener('click',async()=>{try{const t=await csrf();await api('/auth/logout',{method:'POST',headers:{'X-CSRF-Token':t}});location.href='/';}catch{text('action-status','로그아웃하지 못했습니다.');}});
boot();
})();
