(()=>{'use strict';
const $=id=>document.getElementById(id), empty=v=>v===''?null:v;
const node=(tag,text='',cls='')=>{const n=document.createElement(tag);n.textContent=text;if(cls)n.className=cls;return n;};
let csrf=null,epoch=0,listSequence=0,offset=0,selected=null,options=[],mode='new',reuse=null,editingTerm=null,busy=false,attempts=new Map();
const messages={401:'로그인이 필요합니다.',403:'관리자 권한이 없거나 로그인 확인이 만료되었습니다.',422:'입력값을 확인해 주세요. 기록된 결제에는 금액·결제일·증빙 설명이 필요합니다.',409:'다른 변경사항이 있거나 변경할 수 없는 확정 기록입니다. 새로 조회한 뒤 다시 확인해 주세요.',503:'저장소에 연결하지 못했습니다. 저장 완료로 처리하지 않았습니다. 같은 입력으로 다시 시도해 주세요.',0:'요청을 완료하지 못했습니다. 같은 입력으로 다시 시도해 주세요.'};
const details={stale_record:'다른 창에서 수정되었습니다. 창을 닫고 새로 조회한 뒤 수정해 주세요.',pending_term_exists:'먼저 미확정 신청 내역을 수정·확정해 주세요.',fixed_course_cannot_extend:'2개월 고정 과정은 연장하지 않습니다. 다른 기수를 추가해 주세요.',confirmed_history_is_read_only:'확정 이력은 덮어쓰지 않습니다. 수강생 정보 수정 또는 기간 연장을 이용하세요.',linked_member_requires_separate_workflow:'이미 로그인 회원과 연결된 기록은 별도의 회원 수정 절차가 필요합니다.',record_conflict:'이미 같은 수강생의 과정이 있거나 기록 조건이 맞지 않습니다. 보관함도 확인해 주세요.'};
const textError=e=>details[e.detail]||messages[e.status]||messages[0];
// Real transport. The static demo is generated with a separate in-memory implementation.
async function request(path,body){
 const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);
 try{const response=await fetch(path,{method:body===undefined?'GET':'POST',credentials:'same-origin',cache:'no-store',redirect:'error',signal:controller.signal,headers:body===undefined?{}:{'Content-Type':'application/json','X-CSRF-Token':csrf||''},body:body===undefined?undefined:JSON.stringify(body)});
 const data=response.status===204?null:await response.json();
 if(!response.ok)throw {status:response.status,detail:data?.detail};return data;
 }catch(e){if(e.status===401||e.status===403)lock(textError(e));throw e;}finally{clearTimeout(timer);}
}
// END REAL TRANSPORT
const api=async(path,body)=>{const e=epoch,data=await request('/portal/api/admin/manual/'+path,body);if(e!==epoch)throw {stale:true};return data;};
function lock(message){epoch++;selected=null;options=[];csrf=null;$('content').hidden=true;$('gate').hidden=false;$('gate-title').textContent=message;$('rows').replaceChildren();$('terms').replaceChildren();$('profile-detail').replaceChildren();$('logout').hidden=true;document.querySelectorAll('dialog').forEach(d=>d.close());document.querySelectorAll('form').forEach(f=>f.reset());}
function setBusy(value){busy=value;document.querySelectorAll('button[type=submit]').forEach(b=>b.disabled=value);}
async function commit(path,payload){const key=path+JSON.stringify(payload);if(!attempts.has(key))attempts.set(key,crypto.randomUUID());return api(path,{...payload,request_id:attempts.get(key)});}
function fillCourses(){for(const id of ['course-filter','edit-course']){const s=$(id),old=s.value;s.replaceChildren();if(id==='course-filter'){const o=node('option','전체 과정');o.value='';s.append(o);}for(const c of options){const o=node('option',`${c.title}${c.cohort?' / '+c.cohort:''} · ${c.start_month}`);o.value=c.course_id;s.append(o);}if([...s.options].some(o=>o.value===old))s.value=old;}}
async function refreshOptions(){const e=epoch,data=await api('options');if(e!==epoch)return;options=data.items;fillCourses();if(data.has_more)$('message').textContent='과정이 많아 첫 200개만 표시합니다. 전체 과정 탐색은 후속 지원 예정입니다.';}
async function boot(){const e=++epoch;$('gate-title').textContent='관리자 권한을 확인하고 있습니다.';
 try{const me=await request('/auth/me');if(e!==epoch)return;if(me.role!=='admin'){lock('관리자만 사용할 수 있습니다.');return;}const proof=await request('/auth/csrf');if(e!==epoch)return;csrf=proof.csrf_token;await refreshOptions();if(e!==epoch)return;$('identity').textContent=me.display_name+' / 관리자';$('logout').hidden=false;$('gate').hidden=true;$('content').hidden=false;await load();}catch(err){if(e===epoch)$('gate-title').textContent=textError(err);}}
async function load(){const e=epoch,s=++listSequence;$('rows').replaceChildren();$('list-message').textContent='불러오는 중입니다.';$('prev').disabled=true;$('next').disabled=true;
 try{const data=await api('search',{q:$('q').value.trim(),course_id:empty($('course-filter').value),month:empty($('month-filter').value),archived:$('archive-filter').value==='true',offset,limit:20});if(e!==epoch||s!==listSequence)return;
 for(const r of data.items){const tr=node('tr'),td=node('td'),b=node('button',r.name,'name-button');b.addEventListener('click',()=>openDetail(r.enrollment_id));td.append(b,node('small',r.nickname||'닉네임 미등록'));tr.append(td);const course=node('td',r.title);course.append(node('small',r.cohort||'기수 없음'));tr.append(course);tr.append(node('td',r.end_month?(r.start_month===r.end_month?r.start_month:`${r.start_month} ~ ${r.end_month}`):'미확정'));tr.append(node('td',`${r.confirmed_months}개월 확정${r.pending_terms?' / '+r.pending_terms+'건 대기':''}`));for(const x of [r.phone_masked,r.email_masked,r.original_joined_on])tr.append(node('td',x||'—'));const action=node('td'),view=node('button',r.archived?'상세 / 복원':'상세 / 수정');view.addEventListener('click',()=>openDetail(r.enrollment_id));action.append(view);tr.append(action);$('rows').append(tr);}
 $('list-message').textContent=data.items.length?'':'조회 결과가 없습니다. 수강생을 등록하거나 검색 조건을 바꿔 보세요.';$('page-info').textContent=`${offset/20+1}페이지 / 이번 페이지 ${data.items.length}건`;$('prev').disabled=offset===0;$('next').disabled=!data.has_more;
 }catch(err){if(e===epoch&&s===listSequence)$('list-message').textContent=textError(err);}}
function open(id){if(busy)return;attempts.clear();$(id).showModal();}
async function openDetail(id){if(busy)return;const e=epoch;$('message').textContent='상세 정보를 불러오는 중입니다.';
 try{const data=await api('read',{enrollment_id:id});if(e!==epoch)return;selected=data;$('message').textContent='';renderDetail();$('detail').showModal();}catch(err){if(e===epoch)$('message').textContent=textError(err);}}
function renderDetail(){const d=selected;$('detail-title').textContent=d.name+(d.nickname?' / '+d.nickname:'');$('detail-note').textContent=`${d.title} / ${d.cohort||'기수 없음'} · ${d.start_month} 시작 · ${d.archived?'보관된 기록':'수동 등록 기록'}`;$('profile-detail').replaceChildren();for(const [k,v] of [['이메일',d.email],['전화번호',d.phone],['기존 가입일',d.original_joined_on],['회원 계정','수동 기록은 회원 가입·로그인 권한을 만들지 않습니다.']])$('profile-detail').append(node('dt',k),node('dd',v||'—'));
 $('terms').replaceChildren();for(const t of d.terms){const a=node('article','','term-card'),left=node('div');left.append(node('strong',`${t.sequence_no===1?'최초 신청':'추가 신청'} / ${t.months}개월 / ${t.grant_state==='confirmed'?'수강 확정':'미확정'}`));left.append(node('p',`신청금액 ${money(t.quoted_amount_krw)} / 결제기록 ${money(t.paid_amount_krw)}`));left.append(node('small',`${t.applied_on} 신청 · ${receiptName(t.receipt_state)}`));a.append(left);if(t.grant_state==='pending'&&!d.archived){const b=node('button','미확정 신청 수정');b.addEventListener('click',()=>openTerm(t));a.append(b);}else a.append(node('small','확정 이력 유지'));$('terms').append(a);}
 $('edit-profile').disabled=d.archived;$('other-course').disabled=d.archived;$('extend').disabled=d.archived||d.duration_kind==='fixed'||d.terms.some(t=>t.grant_state==='pending');$('archive').textContent=d.archived?'보관 기록 복원':'보관 (삭제)';}
const money=v=>v==null?'미확인':Number(v).toLocaleString('ko-KR')+'원';
const receiptName=s=>({unknown:'영수증 미확인',not_requested:'영수증 미요청',requested:'영수증 요청',recorded_issued:'기존 발급 기록 있음'})[s]||s;
const today=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Seoul'}).format(new Date());
function profileValues(form){const get=n=>empty(form.elements.namedItem(n).value.trim());return {name:get('name'),nickname:get('nickname'),email:get('email'),phone:get('phone'),original_joined_on:get('original_joined_on')};}
function setProfile(form,data={}){for(const key of ['name','nickname','email','phone','original_joined_on'])form.elements.namedItem(key).value=data[key]||'';}
function termFields(host,old={}){host.replaceChildren();const fs=node('fieldset'),legend=node('legend','신청 / 결제 운영 기록'),grid=node('div','','grid'),controls={};fs.append(legend,grid);
 function input(name,label,type='text',value='',required=false){const l=node('label',label),i=node('input');i.name=name;i.type=type;i.value=value??'';i.required=required;if(type==='number'){i.min='0';i.max='100000000';i.step='1';}if(type==='text')i.maxLength=200;l.append(i);grid.append(l);controls[name]=i;return i;}
 function select(name,label,values,selected){const l=node('label',label),s=node('select');s.name=name;for(const [v,t] of values){const o=node('option',t);o.value=v;s.append(o);}s.value=String(selected);l.append(s);grid.append(l);controls[name]=s;return s;}
 select('months','신청기간 (개월)',[[1,'1개월'],[2,'2개월 과정'],[3,'3개월'],[12,'12개월']],old.months||1);input('applied_on','원 신청일','date',old.applied_on||today(),true);input('quoted_amount_krw','신청금액 (원)','number',old.quoted_amount_krw);select('payment_state','결제기록',[['unknown','미확인'],['pending','결제 대기'],['recorded','기존 입금 / 결제 기록 확인']],old.payment_state||'unknown');input('paid_amount_krw','기록된 결제금액 (원)','number',old.paid_amount_krw);input('paid_on','기존 결제일','date',old.paid_on);input('payment_ref','결제 증빙 설명 / 참조','text',old.payment_ref);select('receipt_state','현금영수증',[['unknown','미확인'],['not_requested','미요청'],['requested','요청됨'],['recorded_issued','기존 발급 기록 있음']],old.receipt_state||'unknown');input('receipt_ref','기존 발급 승인번호 / 참조','text',old.receipt_ref);
 const check=node('label','','check'),confirm=node('input');confirm.type='checkbox';confirm.name='confirmed';confirm.checked=old.grant_state==='confirmed';check.append(confirm,node('span','기존 수강 확정 내역을 확인했습니다. 체크한 기간만 확정 인원에 반영됩니다.'));fs.append(check,node('p','이 입력은 결제·영수증 발급을 실행하지 않습니다. 과거 기록을 옮겨 적는 기능입니다.','muted'));host.append(fs);
 function conditional(){const paid=controls.payment_state.value==='recorded';for(const n of ['paid_amount_krw','paid_on','payment_ref']){controls[n].closest('label').hidden=!paid;controls[n].required=paid;}const issued=controls.receipt_state.value==='recorded_issued';controls.receipt_ref.closest('label').hidden=!issued;controls.receipt_ref.required=issued;}
 controls.payment_state.addEventListener('change',conditional);controls.receipt_state.addEventListener('change',conditional);conditional();
 return {setKind(kind){for(const o of controls.months.options)o.disabled=kind==='fixed'?o.value!=='2':o.value==='2';if(controls.months.selectedOptions[0].disabled)controls.months.value=kind==='fixed'?'2':'1';},read(){const value=n=>empty(controls[n].value.trim()),number=n=>value(n)===null?null:Number(value(n)),paid=value('payment_state')==='recorded',issued=value('receipt_state')==='recorded_issued';return {months:Number(value('months')),applied_on:value('applied_on'),confirmed:confirm.checked,quoted_amount_krw:number('quoted_amount_krw'),payment_state:value('payment_state'),paid_amount_krw:paid?number('paid_amount_krw'):null,paid_on:paid?value('paid_on'):null,payment_ref:paid?value('payment_ref'):null,receipt_state:value('receipt_state'),receipt_ref:issued?value('receipt_ref'):null};}};}
let newTermControls,termControls;
function openEditor(kind='new',existing=null){if(busy)return;mode=kind;reuse=existing;const f=$('edit-form');f.reset();$('edit-error').textContent='';setProfile(f,kind==='profile'?selected:existing||{});$('profile-fields').disabled=!!existing;$('create-fields').hidden=kind==='profile';$('edit-course').required=kind!=='profile';$('edit-title').textContent=kind==='profile'?'수강생 정보 수정':existing?'같은 수강생 / 다른 과정 추가':'수강생 수동 등록';$('edit-note').textContent=kind==='profile'?'같은 수강생의 다른 과정에도 이름·연락처 수정이 함께 반영됩니다.':existing?'선택한 수강생에게 명시적으로 연결합니다. 새 회원 계정을 만들지 않습니다.':'실제 회원 가입과 별개인 기존 수강생 기록을 만듭니다.';
 $('new-term').replaceChildren();if(kind!=='profile'){newTermControls=termFields($('new-term'));newTermControls.setKind(options.find(c=>c.course_id===$('edit-course').value)?.duration_kind||'monthly');}$('detail').close();open('editor');}
function openTerm(term=null){if(busy)return;editingTerm=term;$('term-form').reset();$('term-error').textContent='';$('term-title').textContent=term?'미확정 신청 수정':'기간 연장';termControls=termFields($('term-fields'),term||{});termControls.setKind(selected.duration_kind);$('detail').close();open('term-editor');}
async function writeForm(form,errorId,action){if(busy)return;if(!form.reportValidity())return;const e=epoch;setBusy(true);$(errorId).textContent='저장 중입니다.';try{await action();if(e!==epoch)return;$(errorId).textContent='';offset=0;await load();}catch(err){if(e===epoch)$(errorId).textContent=textError(err);}finally{setBusy(false);}}
$('edit-form').addEventListener('submit',event=>{event.preventDefault();const f=event.currentTarget;writeForm(f,'edit-error',async()=>{const reason=f.elements.reason.value.trim();let result;if(mode==='profile'){result=await commit('profile',{enrollment_id:selected.enrollment_id,version:selected.version,learner_version:selected.learner_version,profile:profileValues(f),reason});}else{result=await commit('create',{course_id:$('edit-course').value,profile:reuse?null:profileValues(f),existing_learner_id:reuse?reuse.learner_id:null,learner_version:reuse?reuse.learner_version:null,term:newTermControls.read(),reason});}$('editor').close();$('message').textContent='저장했습니다. 상세 화면에서 기록을 확인하세요.';});});
$('term-form').addEventListener('submit',event=>{event.preventDefault();const f=event.currentTarget;writeForm(f,'term-error',async()=>{const body={enrollment_id:selected.enrollment_id,version:selected.version,reason:f.elements.reason.value.trim(),term:termControls.read()};if(editingTerm)body.term_id=editingTerm.term_id;await commit(editingTerm?'terms/edit':'terms/add',body);$('term-editor').close();$('message').textContent='수강 이력을 저장했습니다.';});});
$('archive-form').addEventListener('submit',event=>{event.preventDefault();const f=event.currentTarget;writeForm(f,'archive-error',async()=>{await commit('archive',{enrollment_id:selected.enrollment_id,version:selected.version,archived:!selected.archived,reason:f.elements.reason.value.trim()});$('archive-editor').close();$('message').textContent=selected.archived?'기록을 복원했습니다.':'기록을 보관했습니다. 보관함에서 복원할 수 있습니다.';selected=null;});});
$('course-form').addEventListener('submit',event=>{event.preventDefault();const f=event.currentTarget;writeForm(f,'course-error',async()=>{const get=n=>f.elements.namedItem(n).value.trim();await commit('courses',{title:get('title'),cohort:empty(get('cohort')),start_month:get('start_month'),duration_kind:get('duration_kind'),price_krw:Number(get('price_krw')),reason:get('reason')});await refreshOptions();$('course-editor').close();$('message').textContent='기록용 과정을 추가했습니다. 판매는 비활성 상태입니다.';});});
$('filters').addEventListener('submit',e=>{e.preventDefault();offset=0;load();});$('prev').addEventListener('click',()=>{offset=Math.max(0,offset-20);load();});$('next').addEventListener('click',()=>{offset+=20;load();});$('new').addEventListener('click',()=>openEditor());$('new-course').addEventListener('click',()=>{if(busy)return;$('course-form').reset();$('course-error').textContent='';open('course-editor');});$('edit-profile').addEventListener('click',()=>openEditor('profile'));$('other-course').addEventListener('click',()=>openEditor('new',selected));$('extend').addEventListener('click',()=>openTerm());$('edit-course').addEventListener('change',()=>newTermControls?.setKind(options.find(c=>c.course_id===$('edit-course').value)?.duration_kind||'monthly'));
$('archive').addEventListener('click',()=>{if(busy)return;$('archive-form').reset();$('archive-error').textContent='';$('archive-title').textContent=selected.archived?'보관 기록 복원':'기록 보관 (삭제)';$('detail').close();open('archive-editor');});document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>{if(!busy)$(b.dataset.close).close();}));document.querySelectorAll('dialog').forEach(d=>d.addEventListener('cancel',e=>{if(busy)e.preventDefault();}));$('retry').addEventListener('click',boot);
$('logout').addEventListener('click',async()=>{if(busy)return;try{await request('/auth/logout',{});lock('로그아웃되었습니다.');}catch(e){$('message').textContent=textError(e);}});
window.addEventListener('pageshow',e=>{if(e.persisted){lock('로그인을 다시 확인합니다.');boot();}});boot();
})();
