function demoUUID(){const a=new Uint8Array(16);crypto.getRandomValues(a);a[6]=(a[6]&15)|64;a[8]=(a[8]&63)|128;const h=[...a].map(v=>v.toString(16).padStart(2,'0')).join('');return h.slice(0,8)+'-'+h.slice(8,12)+'-'+h.slice(12,16)+'-'+h.slice(16,20)+'-'+h.slice(20);}
// Synthetic, in-memory transport for admin-test.html ONLY. Never included in the server image.
const demoCourses=[{course_id:'manual-demo-richon',title:'[가상] 리치온',cohort:'10월 시작',start_month:'2026-10',duration_kind:'monthly',fixed_months:null},{course_id:'manual-demo-free',title:'[가상] 프리리치온',cohort:'10~11월 기수',start_month:'2026-10',duration_kind:'fixed',fixed_months:2}];
const demoLearners=new Map(),demoRecords=new Map(),demoAttempts=new Map();
function demoMonth(start,n){const [y,m]=start.split('-').map(Number),d=new Date(Date.UTC(y,m-1+n,1));return d.toISOString().slice(0,7);}
function demoTerm(months,confirmed,amount){return {term_id:demoUUID(),sequence_no:1,months,grant_state:confirmed?'confirmed':'pending',quoted_amount_krw:amount,payment_state:confirmed?'recorded':'pending',paid_amount_krw:confirmed?amount:null,paid_on:confirmed?'2026-09-20':null,payment_ref:confirmed?'가상 결제기록':null,receipt_state:'not_requested',receipt_ref:null,applied_on:'2026-09-20'};}
function demoSeed(name,nickname,course,months,confirmed=true){const learner_id=demoUUID(),enrollment_id=demoUUID();demoLearners.set(learner_id,{learner_id,name,nickname,email:'sample@example.invalid',phone:'01000000000',original_joined_on:'2026-08-01',learner_version:1});demoRecords.set(enrollment_id,{enrollment_id,learner_id,course_id:course,version:1,archived:false,created_at:new Date().toISOString(),terms:[demoTerm(months,confirmed,months*70000)]});return enrollment_id;}
demoSeed('[가상] 김하늘','하늘집','manual-demo-richon',3);demoSeed('[가상] 이서준','차근차근','manual-demo-richon',12);demoSeed('[가상] 박지우','여백','manual-demo-free',2);demoSeed('[가상] 정다온','다온','manual-demo-richon',1,false);
function demoRecord(id){const r=demoRecords.get(id);if(!r)throw {status:404,detail:'manual_enrollment_not_found'};const l=demoLearners.get(r.learner_id),c=demoCourses.find(c=>c.course_id===r.course_id),n=r.terms.filter(t=>t.grant_state==='confirmed').reduce((a,t)=>a+t.months,0);return {...r,...l,...c,enrollment_id:r.enrollment_id,version:r.version,confirmed_months:n,pending_terms:r.terms.filter(t=>t.grant_state==='pending').length,end_month:n?demoMonth(c.start_month,n-1):null,phone_masked:l.phone?l.phone.slice(0,3)+'-****-'+l.phone.slice(-4):null,email_masked:l.email?l.email.slice(0,1)+'***@'+l.email.split('@')[1]:null};}
function demoValidateTerm(t,kind){if((kind==='fixed'&&t.months!==2)||(kind==='monthly'&&![1,3,12].includes(t.months)))throw {status:422};if(t.confirmed&&t.payment_state==='pending')throw {status:422};if(t.payment_state==='recorded'&&(t.paid_amount_krw==null||!t.paid_on||!t.payment_ref))throw {status:422};if(t.receipt_state==='recorded_issued'&&!t.receipt_ref)throw {status:422};}
function demoUpdateTerm(t,seq){return {...t,term_id:demoUUID(),sequence_no:seq,grant_state:t.confirmed?'confirmed':'pending'};}
async function request(path,body){
 await new Promise(r=>setTimeout(r,80));
 if(path==='/auth/me')return {role:'admin',display_name:'가상 운영자'};
 if(path==='/auth/csrf')return {csrf_token:'demo-not-a-real-credential'};
 if(path==='/auth/logout')return null;
 const action=path.replace('/portal/api/admin/manual/','');
 if(action==='options')return {items:structuredClone(demoCourses),has_more:false};
 if(action==='read')return structuredClone(demoRecord(body.enrollment_id));
 if(action==='search'){const q=body.q.toLowerCase();let list=[...demoRecords.keys()].map(demoRecord).filter(r=>r.archived===body.archived&&(!body.course_id||r.course_id===body.course_id)&&(!q||r.name.toLowerCase().includes(q)||(r.nickname||'').toLowerCase().includes(q)||r.phone===q||(r.email||'').toLowerCase()===q)&&(!body.month||(r.start_month<=body.month&&r.end_month>=body.month)));return {items:structuredClone(list.slice(body.offset,body.offset+body.limit)),offset:body.offset,limit:body.limit,has_more:body.offset+body.limit<list.length};}
 const key=body.request_id,fp=JSON.stringify([action,body]);if(demoAttempts.has(key)){const old=demoAttempts.get(key);if(old.fp!==fp)throw {status:409,detail:'request_key_reused'};return structuredClone(old.result);}
 if(!body.reason||body.reason.length<2)throw {status:422};let result;
 if(action==='courses'){const c={course_id:'manual-'+demoUUID().replaceAll('-',''),title:body.title,cohort:body.cohort,start_month:body.start_month,duration_kind:body.duration_kind,fixed_months:body.duration_kind==='fixed'?2:null};demoCourses.push(c);result={course_id:c.course_id,enabled:false};}
 else if(action==='create'){const course=demoCourses.find(c=>c.course_id===body.course_id);if(!course)throw {status:404};demoValidateTerm(body.term,course.duration_kind);let lid=body.existing_learner_id;if(lid){if(demoLearners.get(lid)?.learner_version!==body.learner_version)throw {status:409,detail:'stale_record'};}else{lid=demoUUID();demoLearners.set(lid,{learner_id:lid,learner_version:1,...body.profile,phone:body.profile.phone?body.profile.phone.replaceAll('-',''):null});}if([...demoRecords.values()].some(x=>x.learner_id===lid&&x.course_id===body.course_id))throw {status:409,detail:'record_conflict'};const eid=demoUUID(),term=demoUpdateTerm(body.term,1);demoRecords.set(eid,{enrollment_id:eid,learner_id:lid,course_id:body.course_id,version:1,archived:false,created_at:new Date().toISOString(),terms:[term]});result={enrollment_id:eid,learner_id:lid,term_id:term.term_id,version:1};}
 else{const old=demoRecord(body.enrollment_id),r=demoRecords.get(body.enrollment_id);if(r.version!==body.version)throw {status:409,detail:'stale_record'};if(r.archived&&action!=='archive')throw {status:409};
 if(action==='profile'){const l=demoLearners.get(r.learner_id);if(l.learner_version!==body.learner_version)throw {status:409,detail:'stale_record'};Object.assign(l,body.profile,{learner_version:l.learner_version+1});}
 else if(action==='archive')r.archived=body.archived;
 else if(action==='terms/add'){if(old.duration_kind==='fixed')throw {status:409,detail:'fixed_course_cannot_extend'};if(r.terms.some(t=>t.grant_state==='pending'))throw {status:409,detail:'pending_term_exists'};demoValidateTerm(body.term,old.duration_kind);r.terms.push(demoUpdateTerm(body.term,r.terms.length+1));}
 else if(action==='terms/edit'){const t=r.terms.find(t=>t.term_id===body.term_id);if(!t||t.grant_state!=='pending')throw {status:409,detail:'confirmed_history_is_read_only'};demoValidateTerm(body.term,old.duration_kind);Object.assign(t,body.term,{grant_state:body.term.confirmed?'confirmed':'pending'});}
 else throw {status:404};r.version++;result={enrollment_id:r.enrollment_id,version:r.version,archived:r.archived};}
 demoAttempts.set(key,{fp,result:structuredClone(result)});return result;
}
